Exception.out: Exception1.o FileException.o Exception.o
	g++ -o $@ Exception1.o FileException.o Exception.o

Exception1.o: Exception1.cpp
Exception.o: Exception.cpp
FileException.o: FileException.cpp
